// Starting points for the /cmux page: twelve colour schemes that are genuinely popular
// in the developer community, and five made for this site.
//
// The two kinds are labelled differently on the page on purpose, because they are
// different claims:
//
//   kind: 'community'  — a real, widely-used scheme with an author and a following.
//     `theme` is the EXACT filename of a theme Ghostty already ships (463 of them
//     live in cmux.app/Contents/Resources/ghostty/themes), so the install writes one
//     `theme = X` line and the user's own installed theme file does the rendering.
//     `credit` names whoever made it. `evidence` is why we call it popular.
//
//   kind: 'example'    — made here. There is no theme file to point at, so `scheme`
//     carries the colours literally: a background, a foreground and all sixteen ANSI
//     slots, written straight into the Ghostty config. That makes it a real colour
//     scheme rather than a rename of somebody else's.
//
// `pal` is the same scheme mapped onto the 14 keys the rest of the site uses, and it
// drives two things: the AFTER preview, and the cmux chrome (pane borders, sidebar
// tint, workspace selection) so the window matches the terminal inside it.
//
// The community palettes are NOT hand-typed. They are generated by
// `node tools/extract-ghostty-themes.js` reading the actual theme files out of the
// installed cmux bundle — 19 hex values each, where one wrong digit would be
// invisible in review and would make the preview lie about what gets installed. Rerun
// that script to refresh them; do not edit the numbers here by hand.
//
// A payload only ever carries a preset ID, never a preset's contents, so a share link
// can name one of these looks but cannot invent a new one — there is no path from a
// link to arbitrary hex in someone's config file through this table.

// ── community palettes, generated from the bundled Ghostty theme files ───────────
const COMMUNITY_PAL = {
  // Dracula — dark, text 13.4:1, comment 3.0:1
  'Dracula': { bg: [40, 42, 54], raised: [68, 71, 90], text: [248, 248, 242], comment: [98, 114, 164], subtle: [59, 60, 68], accent: [189, 147, 249], accent2: [255, 121, 198], cyan: [139, 233, 253], green: [80, 250, 123], red: [255, 85, 85], orange: [255, 187, 135], yellow: [241, 250, 140], pink: [255, 146, 223], blue: [189, 147, 249] },
  // Catppuccin Mocha — dark, text 11.3:1, comment 2.5:1
  'Catppuccin Mocha': { bg: [30, 30, 46], raised: [88, 91, 112], text: [205, 214, 244], comment: [88, 91, 112], subtle: [69, 71, 90], accent: [137, 180, 250], accent2: [245, 194, 231], cyan: [148, 226, 213], green: [166, 227, 161], red: [243, 139, 168], orange: [252, 207, 172], yellow: [249, 226, 175], pink: [242, 174, 222], blue: [137, 180, 250] },
  // TokyoNight Storm — dark, text 9.0:1, comment 2.0:1
  'TokyoNight Storm': { bg: [36, 40, 59], raised: [54, 74, 130], text: [192, 202, 245], comment: [78, 85, 117], subtle: [66, 70, 92], accent: [122, 162, 247], accent2: [187, 154, 247], cyan: [125, 207, 255], green: [158, 206, 106], red: [247, 118, 142], orange: [231, 155, 97], yellow: [224, 175, 104], pink: [187, 154, 247], blue: [122, 162, 247] },
  // Nord — dark, text 9.2:1, comment 2.1:1
  'Nord': { bg: [46, 52, 64], raised: [236, 239, 244], text: [216, 222, 233], comment: [89, 99, 119], subtle: [78, 85, 100], accent: [129, 161, 193], accent2: [180, 142, 173], cyan: [136, 192, 208], green: [163, 190, 140], red: [191, 97, 106], orange: [240, 180, 134], yellow: [235, 203, 139], pink: [180, 142, 173], blue: [129, 161, 193] },
  // Gruvbox Dark Hard — dark, text 12.0:1, comment 4.5:1
  'Gruvbox Dark Hard': { bg: [29, 32, 33], raised: [102, 92, 84], text: [235, 219, 178], comment: [146, 131, 116], subtle: [54, 54, 50], accent: [215, 153, 33], accent2: [177, 98, 134], cyan: [104, 157, 106], green: [152, 151, 26], red: [204, 36, 29], orange: [225, 111, 23], yellow: [215, 153, 33], pink: [211, 134, 155], blue: [69, 133, 136] },
  // Rose Pine — dark, text 13.4:1, comment 3.4:1
  'Rose Pine': { bg: [25, 23, 36], raised: [64, 61, 82], text: [224, 222, 244], comment: [110, 106, 134], subtle: [60, 57, 80], accent: [196, 167, 231], accent2: [235, 188, 186], cyan: [235, 188, 186], green: [49, 116, 143], red: [235, 111, 146], orange: [252, 173, 113], yellow: [246, 193, 119], pink: [196, 167, 231], blue: [156, 207, 216] },
  // Everforest Dark Hard — dark, text 9.4:1, comment 7.1:1
  'Everforest Dark Hard': { bg: [30, 35, 38], raised: [76, 55, 67], text: [211, 198, 170], comment: [166, 176, 160], subtle: [122, 132, 120], accent: [167, 192, 128], accent2: [214, 153, 182], cyan: [131, 192, 146], green: [167, 192, 128], red: [230, 126, 128], orange: [226, 166, 120], yellow: [219, 188, 127], pink: [223, 105, 186], blue: [127, 187, 179] },
  // Kanagawa Wave — dark, text 11.3:1, comment 3.3:1
  'Kanagawa Wave': { bg: [31, 31, 40], raised: [220, 215, 186], text: [220, 215, 186], comment: [114, 113, 105], subtle: [57, 53, 61], accent: [126, 156, 216], accent2: [149, 127, 184], cyan: [106, 149, 137], green: [118, 148, 106], red: [195, 64, 67], orange: [200, 144, 102], yellow: [192, 163, 110], pink: [147, 138, 169], blue: [126, 156, 216] },
  // Atom One Dark — dark, text 7.2:1, comment 3.4:1
  'Atom One Dark': { bg: [33, 37, 43], raised: [50, 56, 68], text: [171, 178, 191], comment: [118, 118, 118], subtle: [50, 54, 61], accent: [97, 175, 239], accent2: [198, 120, 221], cyan: [86, 182, 194], green: [152, 195, 121], red: [224, 108, 117], orange: [235, 168, 117], yellow: [229, 192, 123], pink: [198, 120, 221], blue: [97, 175, 239] },
  // GitHub Dark Default — dark, text 16.0:1, comment 4.1:1
  'GitHub Dark Default': { bg: [13, 17, 23], raised: [230, 237, 243], text: [230, 237, 243], comment: [110, 118, 129], subtle: [72, 79, 88], accent: [88, 166, 255], accent2: [188, 140, 255], cyan: [57, 197, 207], green: [63, 185, 80], red: [255, 123, 114], orange: [220, 109, 24], yellow: [210, 153, 34], pink: [210, 168, 255], blue: [88, 166, 255] },
  // Solarized Dark Patched — dark, text 4.3:1, comment 2.4:1
  'Solarized Dark Patched': { bg: [0, 30, 39], raised: [0, 40, 49], text: [112, 130, 132], comment: [71, 91, 98], subtle: [13, 51, 59], accent: [33, 118, 199], accent2: [198, 28, 111], cyan: [37, 146, 134], green: [115, 138, 5], red: [209, 28, 36], orange: [171, 74, 0], yellow: [165, 119, 6], pink: [89, 86, 186], blue: [33, 118, 199] },
  // Catppuccin Latte — light, text 7.1:1, comment 4.4:1
  'Catppuccin Latte': { bg: [239, 241, 245], raised: [172, 176, 190], text: [76, 79, 105], comment: [108, 111, 133], subtle: [92, 95, 119], accent: [30, 102, 245], accent2: [234, 118, 203], cyan: [23, 146, 153], green: [64, 160, 43], red: [210, 15, 57], orange: [238, 160, 45], yellow: [223, 142, 29], pink: [254, 133, 216], blue: [30, 102, 245] },
};

// ── the presets ──────────────────────────────────────────────────────────────────
// `cm` on each preset is ONLY the settings it deliberately changes; everything else
// stays at the cmux default. That matters because a preset that restated every
// default would silently overwrite settings the user had chosen themselves.
const CMUX_PRESETS = [
  // — community ————————————————————————————————————————————————————————————
  // Ordered by how widely used each one is. `evidence` is what the popularity claim
  // actually rests on, so "community" is a checkable statement rather than a vibe;
  // install counts and star counts were read from the canonical repo or marketplace
  // listing, not estimated.
  {
    id: 'dracula', name: 'Dracula', kind: 'community', theme: 'Dracula',
    credit: 'Zeno Rocha · dracula-theme',
    blurb: 'Deep slate purple with candy pink, cyan and green accents.',
    evidence: '23.6k stars · 10.8M VS Code installs · has its own Wikipedia article',
    cm: { indicatorStyle: 'solidFill' },
  },
  {
    id: 'github-dark', name: 'GitHub Dark', kind: 'community', theme: 'GitHub Dark Default',
    credit: 'GitHub · Primer dark default',
    blurb: "Near-black with crisp white text and GitHub's signature blue.",
    evidence: '19.7M VS Code installs — the most-installed theme in this list',
    cm: { indicatorStyle: 'rail', tintOpacity: 0.04 },
  },
  {
    id: 'one-dark', name: 'One Dark', kind: 'community', theme: 'Atom One Dark',
    credit: 'Atom editor · One Dark syntax',
    blurb: 'Blue-grey slate with soft desaturated syntax. The classic look.',
    evidence: '12.6M VS Code installs · was Atom\u2019s default syntax theme',
    cm: { indicatorStyle: 'leftRail' },
  },
  {
    id: 'catppuccin-mocha', name: 'Catppuccin Mocha', kind: 'community', theme: 'Catppuccin Mocha',
    credit: 'Catppuccin org · Mocha flavour',
    blurb: 'Dark plum base under pastel pinks, mauves and soft blues.',
    evidence: '19.6k org stars · most-configured Neovim scheme on Dotfyle',
    cm: { indicatorStyle: 'wash', tintOpacity: 0.06 },
  },
  {
    id: 'tokyo-night-storm', name: 'Tokyo Night Storm', kind: 'community', theme: 'TokyoNight Storm',
    credit: 'folke, after enkia\u2019s Tokyo Night',
    blurb: 'Navy blue night city, soft lavender text, neon blue accents.',
    evidence: '#1 on Dotfyle Neovim rankings · 8.2k stars · 2.8M VS Code installs',
    cm: { indicatorStyle: 'leftRail' },
  },
  {
    id: 'gruvbox-dark-hard', name: 'Gruvbox Dark', kind: 'community', theme: 'Gruvbox Dark Hard',
    credit: 'Pavel Pertsev (morhetz) · gruvbox',
    blurb: 'Near-black brown with cream text and warm retro oranges.',
    evidence: '15.7k stars · repeatedly named a top pick for long sessions',
    cm: { indicatorStyle: 'typography' },
  },
  {
    id: 'solarized-dark', name: 'Solarized Dark', kind: 'community', theme: 'Solarized Dark Patched',
    credit: 'Ethan Schoonover · Solarized',
    blurb: 'Very dark teal with dim grey-green text. Deliberately flat.',
    evidence: '16.0k stars · the precision-designed original most others react against',
    cm: { indicatorStyle: 'border' },
  },
  {
    id: 'nord', name: 'Nord', kind: 'community', theme: 'Nord',
    credit: 'Arctic Ice Studio · nordtheme',
    blurb: 'Cool arctic blue-greys, low contrast and evenly muted.',
    evidence: '6.9k stars · 1.3M VS Code installs · large cross-app port ecosystem',
    cm: { indicatorStyle: 'border', tintOpacity: 0.05 },
  },
  {
    id: 'kanagawa-wave', name: 'Kanagawa Wave', kind: 'community', theme: 'Kanagawa Wave',
    credit: 'rebelot · kanagawa.nvim',
    blurb: 'Ink-dark indigo with faded wave blue, clay red and dry gold.',
    evidence: '#3 on Dotfyle Neovim rankings · 6.3k stars',
    cm: { indicatorStyle: 'lift' },
  },
  {
    id: 'everforest-dark', name: 'Everforest Dark', kind: 'community', theme: 'Everforest Dark Hard',
    credit: 'sainnhe · Everforest',
    blurb: 'Warm greys and muted forest greens \u2014 the most readable dimmed text here.',
    evidence: '#4 on Dotfyle Neovim rankings · 4.1k stars',
    cm: { indicatorStyle: 'washRail' },
  },
  {
    id: 'rose-pine', name: 'Ros\u00e9 Pine', kind: 'community', theme: 'Rose Pine',
    credit: 'mvllow · Ros\u00e9 Pine collective',
    blurb: 'Muted plum background with dusty rose, gold and pale teal.',
    evidence: '#6 on Dotfyle Neovim rankings · 3.1k stars · 327k VS Code installs',
    cm: { indicatorStyle: 'washRail', tintOpacity: 0.07 },
  },
  {
    id: 'catppuccin-latte', name: 'Catppuccin Latte', kind: 'community', theme: 'Catppuccin Latte',
    credit: 'Catppuccin org · Latte flavour',
    blurb: 'The light one: cool greys on near-white, accents that survive glare.',
    evidence: '19.6k org stars · Catppuccin\u2019s official light flavour',
    cm: { appearance: 'light', indicatorStyle: 'border', tintOpacity: 0.05 },
  },

  // — example themes, made for this site ————————————————————————————————
  // Filled in from the design pass. Each carries a full `scheme` because there is no
  // Ghostty theme file to point at.
];

/** Every preset id, in page order. */
const PRESET_IDS = CMUX_PRESETS.map(p => p.id);

function isPresetId(v) {
  return typeof v === 'string' && v !== '' && PRESET_IDS.indexOf(v) >= 0;
}

function presetById(id) {
  if (!isPresetId(id)) return null;
  return CMUX_PRESETS.find(p => p.id === id) || null;
}

/**
 * The 14-key palette for a preset: read from the bundled theme file for a community
 * preset, carried inline for one of ours. Returns null for an unknown id so callers
 * fall back to the Claude Code palette rather than to a wrong one.
 */
function presetPalette(id) {
  const p = presetById(id);
  if (!p) return null;
  if (p.pal) return p.pal;
  if (p.theme && Object.prototype.hasOwnProperty.call(COMMUNITY_PAL, p.theme)) {
    return COMMUNITY_PAL[p.theme];
  }
  return null;
}

/** What the page needs to render the picker and preview, without the server internals. */
function presetsForClient() {
  return CMUX_PRESETS.map(p => ({
    id: p.id,
    name: p.name,
    kind: p.kind,
    credit: p.credit || '',
    blurb: p.blurb || '',
    evidence: p.evidence || '',
    theme: p.theme || '',
    pal: presetPalette(p.id),
    cm: p.cm || {},
  }));
}

module.exports = {
  CMUX_PRESETS,
  COMMUNITY_PAL,
  PRESET_IDS,
  isPresetId,
  presetById,
  presetPalette,
  presetsForClient,
};
