// GENERATED by tools/extract-codex-syntax-themes.js — do not edit by hand.
//
// Token colours for every syntax theme Codex CLI 0.147.0 ships (tui.theme). The 22
// bat-overlapping themes were rendered through bat with COLORTERM=truecolor and the
// colours parsed off the ANSI output; the 5 syntect built-ins were parsed from their
// canonical upstream .tmTheme files. Both bat and Codex embed this theme set from the
// two-face crate, so these are the colours Codex actually renders.
//
// fg    plain text          com  comments            kw   storage keywords (function/const)
// kw2   control keywords    str  strings             fn   function names
// num   numbers             light  made for a light terminal (fg is dark)

const CODEX_SYNTAX = {
  'base16': {"fg":"#c0c0c0","com":"#c0c0c0","kw":"#c0c0c0","kw2":"#c0c0c0","str":"#c0c0c0","fn":"#c0c0c0","num":"#c0c0c0","light":false},
  'base16-256': {"fg":"#c0c0c0","com":"#c0c0c0","kw":"#c0c0c0","kw2":"#c0c0c0","str":"#c0c0c0","fn":"#c0c0c0","num":"#c0c0c0","light":false},
  'base16-eighties-dark': {"fg":"#d3d0c8","com":"#747369","kw":"#cc99cc","kw2":"#d3d0c8","str":"#99cc99","fn":"#6699cc","num":"#f99157","light":false},
  'base16-mocha-dark': {"fg":"#d0c8c6","com":"#7e705a","kw":"#a89bb9","kw2":"#d0c8c6","str":"#beb55b","fn":"#8ab3b5","num":"#d28b71","light":false},
  'base16-ocean-dark': {"fg":"#c0c5ce","com":"#65737e","kw":"#b48ead","kw2":"#c0c5ce","str":"#a3be8c","fn":"#8fa1b3","num":"#d08770","light":false},
  'base16-ocean-light': {"fg":"#4f5b66","com":"#a7adba","kw":"#b48ead","kw2":"#4f5b66","str":"#a3be8c","fn":"#8fa1b3","num":"#d08770","light":true},
  'catppuccin-frappe': {"fg":"#c6d0f5","com":"#949cbb","kw":"#ca9ee6","kw2":"#ca9ee6","str":"#a6d189","fn":"#8caaee","num":"#ef9f76","light":false},
  'catppuccin-latte': {"fg":"#4c4f69","com":"#7c7f93","kw":"#8839ef","kw2":"#8839ef","str":"#40a02b","fn":"#1e66f5","num":"#fe640b","light":true},
  'catppuccin-macchiato': {"fg":"#cad3f5","com":"#939ab7","kw":"#c6a0f6","kw2":"#c6a0f6","str":"#a6da95","fn":"#8aadf4","num":"#f5a97f","light":false},
  'catppuccin-mocha': {"fg":"#cdd6f4","com":"#9399b2","kw":"#cba6f7","kw2":"#cba6f7","str":"#a6e3a1","fn":"#89b4fa","num":"#fab387","light":false},
  'coldark-cold': {"fg":"#111b27","com":"#3c526d","kw":"#a04900","kw2":"#a04900","str":"#116b00","fn":"#7c00aa","num":"#755f00","light":true},
  'coldark-dark': {"fg":"#e3eaf2","com":"#8da1b9","kw":"#e9ae7e","kw2":"#e9ae7e","str":"#91d076","fn":"#c699e3","num":"#e6d37a","light":false},
  'dark-neon': {"fg":"#ffffff","com":"#7c7c7c","kw":"#cfcb90","kw2":"#66ccff","str":"#ccff66","fn":"#f8f8f8","num":"#ffffff","light":false},
  'dracula': {"fg":"#f8f8f2","com":"#6272a4","kw":"#8be9fd","kw2":"#ff79c6","str":"#f1fa8c","fn":"#50fa7b","num":"#bd93f9","light":false},
  'github': {"fg":"#333333","com":"#969896","kw":"#a71d5d","kw2":"#a71d5d","str":"#183691","fn":"#795da3","num":"#0086b3","light":true},
  'gruvbox-dark': {"fg":"#fbf1c7","com":"#928374","kw":"#8ec07c","kw2":"#fb4934","str":"#b8bb26","fn":"#b8bb26","num":"#d3869b","light":false},
  'gruvbox-light': {"fg":"#282828","com":"#928374","kw":"#427b58","kw2":"#9d0006","str":"#79740e","fn":"#79740e","num":"#8f3f71","light":true},
  'inspired-github': {"fg":"#323232","com":"#969896","kw":"#a71d5d","kw2":"#a71d5d","str":"#183691","fn":"#795da3","num":"#0086b3","light":true},
  'monokai-extended': {"fg":"#f8f8f2","com":"#75715e","kw":"#66d9ef","kw2":"#f92672","str":"#e6db74","fn":"#a6e22e","num":"#ae81ff","light":false},
  'monokai-extended-bright': {"fg":"#f8f8f2","com":"#75715e","kw":"#66d9ef","kw2":"#f92672","str":"#e6db74","fn":"#a6e22e","num":"#ae81ff","light":false},
  'monokai-extended-light': {"fg":"#49483e","com":"#75715e","kw":"#0089b3","kw2":"#f9005a","str":"#998f2f","fn":"#679c00","num":"#ae81ff","light":true},
  'monokai-extended-origin': {"fg":"#f8f8f2","com":"#75715e","kw":"#66d9ef","kw2":"#f92672","str":"#e6db74","fn":"#a6e22e","num":"#ae81ff","light":false},
  'one-half-dark': {"fg":"#dcdfe4","com":"#5c6370","kw":"#c678dd","kw2":"#c678dd","str":"#98c379","fn":"#61afef","num":"#e5c07b","light":false},
  'one-half-light': {"fg":"#383a42","com":"#a0a1a7","kw":"#a626a4","kw2":"#a626a4","str":"#50a14f","fn":"#0184bc","num":"#c18401","light":true},
  'solarized-dark': {"fg":"#839496","com":"#586e75","kw":"#268bd2","kw2":"#859900","str":"#2aa198","fn":"#b58900","num":"#6c71c4","light":false},
  'solarized-light': {"fg":"#657b83","com":"#93a1a1","kw":"#268bd2","kw2":"#859900","str":"#2aa198","fn":"#b58900","num":"#6c71c4","light":true},
  'sublime-snazzy': {"fg":"#f8f8f2","com":"#686868","kw":"#9aedfe","kw2":"#ff5c57","str":"#f3f99d","fn":"#9aedfe","num":"#f1f1f0","light":false},
  'zenburn': {"fg":"#dedede","com":"#87ae86","kw":"#fffb9d","kw2":"#fed6af","str":"#d68686","fn":"#fffd87","num":"#dedede","light":false},
};

module.exports = { CODEX_SYNTAX };
